AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  twilio-to-sqs

  Sample SAM Template for twilio-to-sqs

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TwilioWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: twilio-webhook/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        TwilioWebhook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt CatPrinterQueue.QueueName
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:twilio/webhook-*
      Environment:
        Variables:
          QUEUE_URL: !Ref CatPrinterQueue
          TWILIO_AUTH_TOKEN: '{{resolve:secretsmanager:twilio/webhook:SecretString:TWILIO_AUTH_TOKEN}}'
  CatPrinterQueue:
    Type: AWS::SQS::Queue

Outputs:
  TwilioWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Twilio Webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  
  TwilioWebhookFunction:
    Description: "Twilio Webhook Lambda Function ARN"
    Value: !GetAtt TwilioWebhookFunction.Arn
  
  TwilioWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for TwilioWebhookFunction"
    Value: !GetAtt TwilioWebhookFunctionRole.Arn